apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nacos-server
  selfLink: /api/v1/namespaces/default/services/nacos-server
spec:
  ports:
  - port: 8848
    protocol: TCP
    targetPort: 8848
  selector:
    app: nacos-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
